backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: content/images
public_folder: ../images

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # - { label: Path, name: path }
      - { label: "Template Key", name: templateKey, widget: hidden, default: "blog-post" }
      - { label: Title, name: title, widget: string }
      # - { label: Date, name: date, widget: date }
      - { label: Date, name: date, widget: datetime }
      - { label: "Audio Link", name: audio, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, widget: list, required: false }

  - name: "pages"
    label: Pages
    files:
      - file: "src/pages/live/index.md"
        label: "Live"
        name: "live"
        fields:
          - { label: "Template Key", name: templateKey, widget: hidden, default: "live-page" }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
